{1}{1}25.000
{6982}{7021}Pare!!
{7192}{7224}Matar Lara Croft
{7457}{7530}Hey, olá todos.
{7962}{7996}Sua vadia!!
{8062}{8112}Pra valer não, Lara.
{8114}{8184}Agora ele está todo destruído...
{8186}{8278}Este é meu melhor modelo.|Isto é um desastre.
{8280}{8378}Ele foi programado para parar|antes de arrancar minha cabeça?
{8380}{8472}É, bem, eu "acho" que não.
{8512}{8548}Mas você disse para|ser desafiador, então...
{8570}{8608}Hence, a vida é real.
{8752}{8790}Hmmmm, pegou pra valer de novo.
{8790}{8838}Pobre Simon.
{8844}{8888}O que ela fez com você?
{10274}{10312}Muito engraçado.
{10312}{10366}Só estou tentando|torná-la uma dama.
{10434}{10468}E uma dama deveria ser modesta.
{10470}{10552}É, uma dama deveria ser modesta.
{10604}{10684}Veneza, Itália
{10920}{10980}Irmãos e irmãs...
{10982}{11056}Hoje é 15 de Maio,
{11058}{11166}o primeiro dia|do alinhamento dos planetas
{11172}{11276}e sequer estamos perto de|descobrir a localização da chave.
{11278}{11312}Isso significa...
{11318}{11372}Que estamos contra o tempo.
{11374}{11476}O que não é aceitável.
{11478}{11596}Sr. Powell,|Por favor, qual sua explicação?
{11598}{11704}Não tenho explicações.|Nem desculpas.
{11706}{11806}Exceto que, novamente e|respeitosamente devo lembrar o Conselho...
{11806}{11904}que estamos trabalhando baseados|em antigos modelos cósmicos...
{11942}{11996}que antecedem Aristóteles.
{11998}{12092}Mas estou feliz em anunciar|que estamos quase lá.
{12094}{12172}E estou muito confiante...
{12174}{12280}de que teremos nossa resposta a tempo|para o alinhamento dos planetas.
{12282}{12374}Então, teremos a posse|da chave em...
{12402}{12444}uma semana.
{12446}{12528}Certamente, uma semana.
{12530}{12638}Parece bom, Sr. Powell,|mas lembre-se...
{12640}{12710}teremos apenas|uma única oportunidade...
{12712}{12792}para encontrar as duas metades|do triângulo.
{12794}{12854}E se falharmos...
{12855}{12966}teremos que esperar outros 5000 anos.
{13008}{13056}Eu não sei do senhor,|mas isso é muito mais tempo...
{13059}{13118}do que eu pretendo|investir nesta causa.
{13158}{13204}Nós deveremos estar prontos.
{13250}{13287}Confie em mim.
{13568}{13627}- Nós não estamos prontos, não é?|- Não.
{13791}{13876}Bom dia, Lara.|E que bonita manhã!!
{13898}{13934}Volte ao trabalho. Estou receoso.
{13990}{14038}É hora de aventura.
{14104}{14150}Egito de novo.
{14176}{14228}Nada a não ser pirâmides e areia.
{14230}{14300}Eu sei.|Pega todo mundo onde puder.
{14394}{14444}Galeão Espanhol?
{14498}{14548}Você sabe que dia|é hoje, Hillary?
{14588}{14658}Sim, claro.
{14695}{14724}Dia 15.
{14762}{14852}E esse nunca é um dia bom.
{15202}{15280}Lord Richard Croft Desaparecido no|Campo de Batalha. 15 de Maio de 1985.
{15387}{15446}Sinto sua falta, papai.
{15494}{15560}Gostaria de ter de volta o tempo|que foi roubado de nós.
{16146}{16206}Meu pai adoraria|estar vendo isso.
{16252}{16342}Esta noite Plutão e Netuno|se alinham com Urano.
{16345}{16406}É o primeiro estágio|do alinhamento dos nove planetas...
{16408}{16486}terminando|num eclipse solar total.
{16488}{16560}Isso só acontece uma vez|a cada 5000 anos.
{16562}{16610}Quando é o eclipse?
{16610}{16672}Daqui a uma semana.
{16674}{16766}Mas há muito para se|ver até lá.
{16806}{16848}Inacreditável.
{17632}{17704}Queria tanto que você se lembrasse dela.|Ela a amava tanto...
{17706}{17748}Mamãe!
{17788}{17854}Eu também queria lembrar dela.
{17854}{17924}Mas ainda tenho você, papai.
{17924}{17964}Isso é verdade.
{18070}{18166}O alinhamento exato dos planetas|necessário para ativar o triângulo...
{18168}{18308}só acontece a cada 5000 anos.
{18308}{18388}Mas parece ter tempo,|o tempo necessário...
{18390}{18478}para a pequena Lara crescer...
{18480}{18528}e encontrá-lo.
{21462}{21498}Bryce!
{21542}{21580}Oi galera.
{21602}{21648}- O que está acontecendo??|- Bryce!
{21686}{21756}Ok, ok.|Estou indo. Tô indo.
{21838}{21904}Nós temos 83 quartos.|Porque você não pode morar na casa?
{21906}{21974}Bem, eu sou um espírito livre, eu...
{21976}{22010}Tá bom.
{22056}{22084}Que cheiro é esse?
{22086}{22154}5:00 da manhã. Vamos.
{22236}{22288}É melhor ser coisa boa.
{22388}{22418}É um relógio.
{22420}{22512}Eu o encontrei noite passada.|Ele estava funcionando.
{22600}{22662}Deve ser só um destes|que fazem "tic tac's", certo?
{22696}{22736}Ele estava escondido numa sala secreta.
{22776}{22822}Bryce!
{22826}{22868}Não brinca.
{22868}{23004}Lara, é um relógio. Faz tic-tac.|Informa as horas. Tá errado.
{23006}{23052}Ele passou a funcionar...
{23054}{23116}noite passada durante o primeiro estágio|do alinhamento.
{23252}{23304}Tá, preciso de café...
{23420}{23474}Ok, aí vamos nós.
{23538}{23592}Pra mim, parece normal.
{23592}{23640}Tá bom, continue olhando.
{23736}{23822}Seu café, senhor.|Descafeinado com leite integral.
{23870}{23958}Oh, campeão.|Óleo de garagem fervido no vapor..
{24064}{24136}Espere. O que você fez?
{24138}{24206}- Sei lá. O que eu fiz?|- O que é aquilo?
{24208}{24286}Sei lá. Eu só larguei|a fibra óptica.
{24288}{24328}O que é aquilo?
{24328}{24420}- Oh, "bugger"!|- "Bugger".
{24528}{24580}Parafuso 13 até o quarto quadrante.
{24612}{24718}- Parafuso 14 até o quarto quadrante.|- Oh, por favor.
{24752}{24838}É meu mapa,|Deste modo saberei de onde vieram.
{24840}{24888}É uma camuflagem.
{25168}{25216}Tá bom.
{25464}{25512}Escondido aí dentro.
{25576}{25605}O que é isso?
{25733}{25778}O Olho que Tudo Vê.
{26078}{26189}Lote 121, um relógio Luis XV|Ormolu.
{26192}{26292}Mostrado à minha esquerda,|1 milhão e 800 mil libras.
{26294}{26370}1,800,000. Obrigado.|Um milhão e oitocentos. 1,900,000.
{26372}{26430}Dois milhões de libras.|Dois milhões de libras agora.
{26436}{26552}2.100,000, 2.100,000 agora.|2.100,000 libras.
{26558}{26618}Quem me dá 2.100,000 libras?
{26620}{26708}Alguém mais? Dois milhões e cem.|2.200,000. Obrigado, senhor.
{26708}{26756}2.200,000 libras agora.
{26758}{26845}A 2.200,000.|2.300,000.
{26848}{26895}Dois milhões e trezentas.|2.400,000.
{26896}{27004}Lance da senhora, 2.400,000 libras.|2.400,000.
{27005}{27048}E o senhor?.|Dois milhões e quinhentas?? Não.
{27048}{27182}2.400,000 libras, então. Lance da senhora|a dois e quatrocentos. 2.500,000.
{27184}{27267}Estará num novo lugar a 2.500,000 libras.
{27270}{27356}Algo mais que 2.500,000 libras?
{27358}{27388}Vendido.
{27448}{27506}Lara, minha querida!
{27508}{27600}- Sr. Wilson.|- Vamos ao meu escritório. Eu levo isso.
{27600}{27666}Lara Croft. Eu não acredito.
{27722}{27789}- Isso só vai levar um minuto.|- Oi.
{27892}{27956}Você ainda finge ser|uma fotógrafa de jornal?
{27984}{28072}Você sabe, eu acho até legal|que você tenha um trabalho...
{28096}{28146}mesmo que seja obviamente|uma fachada.
{28173}{28268}Então, Alex, você ainda finge|ser um arqueologista?
{28392}{28430}Nós temos sempre que|brigar deste jeito?
{28433}{28508}Quero dizer, talvez não.
{28510}{28562}- Talvez sim.|- Porque?
{28564}{28624}- Você roubou meus pergaminhos.|- Roubei? Roubei?
{28627}{28673}De você? Você sabe, engraçado.|Você sabe...
{28676}{28742}Não é como se você|realmente os tivesse, ou algo assim.
{28780}{28836}Ei, você é a caça-tumba.
{28838}{28890}Sr. West estamos prontos.
{28892}{28964}Oh, acho que seus clientes precisam de você.
{28989}{29062}Vá em frente.|Estão te esperando.
{29064}{29164}Depois de tudo, como você mesmo disse,|''Isso é só um negócio.''
{29166}{29227}Certo?|Então vá negociar.
{29228}{29262}Vai.
{29833}{29955}Lara, este objeto é único.
{29956}{30023}Somente um dos relógios|está funcionando.
{30024}{30108}Emite luz, como o olho menor.
{30111}{30158}Mas parece|ficar mais intenso.
{30160}{30230}E também está marcando o tempo|de trás pra frente
{30232}{30312}como se, não apenas marcando tempo|mas fazendo uma contagem regressiva.
{30312}{30360}- Sim.|- E olhe a parte de trás.
{30361}{30450}É como se se encaixasse em|algo, assim como uma chave.
{30523}{30600}Sim. Sim, fascinante.
{30602}{30695}- Inacreditavelmente belo.|- Uma vez meu pai me contou...
{30696}{30756}sobre um triângulo mágico|gravado no Olho que tudo Vê.
{30756}{30830}Ele disse que isso daria ao portador|um poder extraordinário,
{30833}{30892}o poder de controlar o tempo.
{30894}{30989}Ele o chamou de Triângulo da Luz.|Já ouviu falar disso?
{30992}{31044}Não. Não, nunca ouvi.
{31158}{31288}Seu pai, sempre dirigiu|o próprio curso.
{31288}{31344}Ele foi um grande homem.
{31412}{31470}Gostaria de um vinho do porto?
{31472}{31558}- Realmente é muito bom.|- Não.
{31561}{31612}Não posso ajudá-la, Lara.
{31612}{31724}Este relógio na verdade é um mistério.
{32205}{32252}- Alô.|- Lara?
{32252}{32300}Alô, é o Sr. Wilson.
{32300}{32394}Sim, eu. Bem, Eu|Veja, tenho outra opinião...
{32395}{32462}sobre o relógio.
{32464}{32508}Existe um homem que|talvez possa ajudá-la.
{32510}{32606}Eu dei seu número a ele.|Seu nome é Manfred Powell.
{32608}{32656}Você deveria vê-lo.
{32658}{32712}Obrigado. Eu o verei.
{32714}{32780}- Tchau, Lara.|- Se cuida.
{32782}{32824}Obrigado.
{32878}{32918}Bugger.
{33350}{33396}Perdoe-me.
{33728}{33762}Senhorita Croft.
{33764}{33832}- Ah, Sr. Powell.|- Oh, não, não, não. Pelos céus, não.
{33834}{33926}Na verdade sou seu sócio, Sr. Pimms.
{33928}{34008}- Sr. Pimms?|- Sim, como a bebida.
{34264}{34308}Sim, ela está aqui.
{34380}{34452}O que o Sr. Powell faz?
{34454}{34506}Ele é advogado.|Sou seu assistente legal...
{34508}{34608}Recentemente neste serviço|mas gostando do trabalho variado.
{34650}{34720}- Um advogado..|- Isto não é óbvio?
{34770}{34816}Lady Croft, muito prazer.
{34816}{34888}- Manfred Powell, QC.|- Bom dia.
{34890}{34976}Eu acho que você é uma autoridade|em coisas antigas e mitológicas.
{34980}{35014}Bom, Eu viajo.
{35014}{35100}Não, não, o Sr. Wilson disse que você|é realmente A arqueologista.
{35102}{35148}Por favor.
{35150}{35212}Oh, ele é tão gentil.
{35214}{35260}Acredito que ele tenha|conhecido seu pai.
{35324}{35366}Sim, eles eram grandes amigos.
{35390}{35488}Eu mesmo tive a honra de encontrá-lo|uma vez em Veneza.
{35490}{35568}Fiquei triste|quando soube de sua morte.
{35680}{35734}Este é o relógio que mencionei.
{35830}{35858}Muito interessante.
{35940}{35990}É uma vergonha que você|tenha trazido só fotografias.
{36052}{36140}No entanto, é fascinante.
{36142}{36212}Você disse que ele começou a funcionar|na noite do alinhamento.
{36212}{36238}Sim.
{36354}{36432}- Você disse que é um advogado?|- Sim.
{36432}{36506}E o estudo de relógios, é só um hobby?
{36508}{36580}Isso é uma obsessão.
{36582}{36654}Realmente minha especialidade|é estar ao redor de antiguidades.
{36692}{36732}Mas a origem deste relógio...
{36734}{36790}me fascina completamente.
{36860}{36912}Eu acho que nunca vi|nada tão bonito...
{36914}{36964}pelo qual sei tão pouco.
{37096}{37148}Isto é um tormento prazeroso.
{37192}{37262}Minha ignorância me diverte.
{37294}{37366}''Minha ignorância me diverte.''
{37452}{37516}Sim, bem, Nós sempre achamos|sua ignorância um divertimento.
{37518}{37574}Powell, que seja, não é ignorante.
{37644}{37688}Ele é um mentiroso.
{38014}{38078}- Precisa de algo?|- Não. Obrigada, Hillary.
{38080}{38152}- Não fique acordada até tarde.|- Não ficarei.
{39126}{39172}Time de frente, espere meu comando.
{39310}{39384}Em posição aguardando ordens.
{41396}{41424}Desgraçados!
{41442}{41478}Que inferno!!
{41634}{41672}Pra esquerda.|Pra esquerda.
{42208}{42244}Vamos lá, Simon!
{42414}{42432}Bugger!
{45030}{45094}Lara, Lara, você está aí?|Responda!
{45132}{45180}Lara, tá me ouvindo?|Você tá bem?
{45238}{45308}Estou na sala de ferramentas.|Estão roubando meu maldito relógio.
{45308}{45338}Eu sei. Eu os vi.
{45454}{45508}- Você será meus olhos.|- Você está armada?
{45558}{45604}Na verdade, estou.
{45604}{45662}Tá bom.|Três caras maus.
{45664}{45714}Número um de pé|perto do Aston Martin.
{45716}{45740}Certo.
{45812}{45858}Bingo!
{46238}{46304}- Próximo.|- Ok, número dois,
{46306}{46360}agachado perto da McLaren.
{46432}{46460}Oh, bugger!
{46704}{46778}- Você está bem?|- Acabei de achar as chaves dos meus carros!
{47126}{47180}É isso aí parceira.|Boa essa.
{49036}{49098}Eu acho que já foram embora.
{49126}{49174}Mas conseguiram levar|o que vieram buscar.
{49222}{49260}Desculpe por aquilo.
{49280}{49316}Tudo bem.
{50316}{50346}Alô?
{50464}{50540}Que diabos aconteceu aqui?
{50744}{50800}- Bom dia.|- Senhorita Lara Croft?
{50802}{50864}Sim. Tem algo pra mim?
{51108}{51180}Eu acordei esta manhã,|e simplesmente odiava tudo...
{51182}{51256}Tá bom. Obrigado.
{51368}{51447}Quem são Stribling, Clive|e Winterset?
{51448}{51520}- Parecem um bando de advogados.|- Pois eles são um bando de advogados.
{51562}{51642}- Tá, eu vou ficar na minha.|- Você é abelhudo.
{51644}{51694}Eu não sou abelhudo.|Só falei o nome.
{51700}{51780}Era um nome engraçado.|Só perguntei que nome era aquele.
{51872}{51906}É do meu pai.
{51966}{52020}Isso foi escrito antes dele morrer...
{52022}{52114}e entregue somente hoje|conforme suas instruções.
{52116}{52184}- Caramba!|- Santa merd*
{52420}{52476}''Para ver o mundo|num grão de areia...
{52476}{52541}e o céu numa flor selvagem...
{52544}{52628}segure o infinito|na palma da sua mão...
{52630}{52684}e a eternidade em uma hora.''
{52720}{52758}William Blake.
{53396}{53432}O Olho Que Tudo Vê.
{53988}{54032}Querida filha...
{54034}{54109}Eu sabia que iria descobrir.
{54112}{54176}Se está lendo esta carta,|É porque não estou mais com você...
{54178}{54224}e sinto sua falta...
{54226}{54298}e te amarei sempre, sempre.
{54300}{54376}Isso também significa que falhei...
{54378}{54462}e que você deverá carregar nos ombros|uma terrível tarefa.
{54464}{54591}Lara, tenho certeza de que você|encontrou o relógio que eu escondi.
{54591}{54680}O relógio é a chave, Lara.
{54682}{54803}Ela vai abrir um lugar escondido|de duas peças de um objeto sagrado.
{54803}{54896}É o triângulo sagrado que mencionei|quando você era pequena.
{54897}{55014}O Triângulo da Luz.|Mas isso não é estória de ninar.
{55016}{55102}O Triângulo foi forjado de um metal|encontrado na cratera do meteoro...
{55108}{55156}que caiu na Terra|no exato momento...
{55158}{55228}do alinhamento anterior|dos nove planetas.
{55230}{55291}O Povo da Luz construiu|uma grande cidade nesta cratera...
{55291}{55386}onde adoravam o Triângulo|pela sua habilidade de controlar o tempo.
{55388}{55498}Ele dá ao possuidor um poder que pode|ser usado para o bem ou para o mal.
{55500}{55582}O abuso deste poder levou|à destruição da cidade.
{55652}{55742}Para se assegurarem de que ninguém|jamais usaria este poder novamente...
{55744}{55796}Eles o partiram|em duas partes...
{55797}{55880}e as esconderam em|lugares opostos na Terra.
{55882}{55982}Lara, você se lembra do jasmim|que só nasce em um templo...
{55984}{56053}junto da antiga trilha Khmer|no Cambodja?
{56054}{56100}O encontre e você terá|encontrado a entrada...
{56103}{56156}para a Tumba da Dança da Luz...
{56158}{56230}onde a primeira metade|do triângulo está escondida.
{56236}{56297}Você deve estar lá|no exato momento...
{56298}{56380}da segunda fase|do alinhamento dos planetas.
{56380}{56452}Você deve se apressar.|Não resta muito tempo.
{56452}{56500}E com os planetas|se alinhando...
{56503}{56559}o mundo correrá|uma grande perigo...
{56560}{56652}por causa duma sociedade|secreta conhecida como Illuminati,
{56653}{56716}perturbados, homens perigosos...
{56718}{56766}que procuram realizar|uma antiga profecia...
{56766}{56822}reunindo as duas partes...
{56824}{56942}e obtendo seus terríveis|e assustadores poderes.
{56944}{57041}É isto que você deve evitar|a todo custo.
{57042}{57150}Então, Lara, eu estou pedindo|que você complete meu trabalho...
{57152}{57272}encontrar e destruir|as duas metades do Triângulo.
{57334}{57452}Como você acha que vai para o Cambodja|trazer o relógio de volta em 15 horas?
{57452}{57502}Eu vou cobrar um favor.
{57532}{57609}- Que tipo de favor?|- Bom, isso é segredo.
{57610}{57676}Se eu te contar,|Terei que te matar.
{57908}{57956}Senhorita Croft, está no alvo?|Câmbio.
{57958}{58028}Bem no alvo.|Obrigado rapazes. Pronto e desligo.
{59030}{59076}Mas que previsível.
{59191}{59254}Alex West.
{59259}{59316}O que você está fazendo aqui?
{60284}{60364}Nós temos 72 minutos|até o próximo alinhamento.
{60366}{60412}Temos que trabalhar mais rápido.
{60684}{60710}Vamos, rapazes!
{61636}{61709}Vamos, rapazes! Vamos, rapazes! Puxem!
{61712}{61740}Puxem! Está vindo!
{62056}{62086}Bom.
{62864}{62958}Então, algum sinal da Lady Croft?
{62959}{62986}Ainda não.
{62988}{63070}Lara está defasada.|Ela é boa, não entenda mal...
{63076}{63138}mas ela está nessa pela glória...
{63140}{63196}enquanto eu estou nisso pelo dinheiro.
{63197}{63250}Felizmente.
{63252}{63340}- Pra dentro da barriga da fera.|- E fora do rabo do demônio.
{64956}{65000}Jasmim.
{67544}{67626}Lembrem-se, o que estamos procurando|está escondido não apenas no espaço...
{67628}{67664}mas também no tempo.
{67692}{67736}O relógio é a chave.
{67952}{68000}Meu Deus.
{68196}{68272}''Retorne o ferro para|o abraço da pedra...
{68274}{68322}a roda do céu irá girar.
{68324}{68390}Exumando a luz|do túmulo aquático...
{68428}{68492}para receber o presente do céu...
{68494}{68572}você está condenado|a profundidade do inferno.''
{68608}{68698}Certo. Toque em qualquer coisa|e terá a cabeça cortada fora.
{68748}{68798}Nós temos dois minutos, Sr. West.
{68800}{68884}Você é o caçador de tumbas.|Decifre isso.
{69256}{69324}Tempus fugit.
{69324}{69396}Isso mesmo, ''o tempo voa.''
{69396}{69446}São as espadas!
{69448}{69548}Vamos, rapazes. Venham aqui em cima.|Me ajudem com isso.
{69656}{69736}Isso aí. Vamos.|Descendo.
{69738}{69786}Quero todas para baixo.
{69788}{69858}Peguem-nas, carreguem-na|através das escadas.
{69860}{69898}Vamos empurrar.
{69932}{70054}Certo. Agora deslizem|nas fendas aqui.
{70060}{70164}Posicionaremos o relógio aqui|no exato momento do alinhamento.
{70164}{70220}Vamos. Vamos! Movam-se!
{70258}{70316}tá devagar, meninas, muito devagar.|Vamos!.
{70500}{70548}- É isso.|- Contando.
{70592}{70660}- O tempo precisa ser exato.|- Não brinca.
{71252}{71292}Sessenta segundos.
{71294}{71374}59, 58...
{71380}{71436}57, 56...
{71438}{71528}55, 54...
{71528}{71620}53, 52, 51...
{71620}{71670}Cinqüenta segundos.
{71816}{71886}Cessar fogo!|Cessar fogo!
{72004}{72080}- Continue contando.|- Você está cometendo um grande erro!
{72082}{72152}41, 40...
{72152}{72232}39, 38...
{72234}{72276}- 37...|- Turista visa?
{72276}{72350}- Não, Estou trabalhando.|- Senhorita Croft, me diga...
{72352}{72400}há uma boa razão|para eu manter você viva?
{72402}{72492}Há. Este não é o verdadeiro Olho.
{72494}{72590}- Este é o Olho verdadeiro.|- Realmente não é.
{72592}{72618}É uma imagem do espelho.
{72620}{72702}Eu acho que você está tentando me enganar|e tirar meu lugar ao sol.
{72704}{72752}Porque eu tentaria te enganar|de qualquer forma agora?
{72752}{72824}Eu preciso de você agora para roubar a metade|então posso roubar de você depois.
{72826}{72876}Você está blefando.|Julius, faça uma nota mental.
{72878}{72934}Mate Senhorita Croft|se ela tentar qualquer coisa.
{72940}{72992}Sim, senhor, Sr. Powell.
{72994}{73076}Nós podemos fazer isso do meu jeito|ou voltar no próximo alinhamento...
{73078}{73130}e você será bem-vindo|para tentar me matar então.
{73132}{73208}Em, hum, digamos|daqui a outros 5000 anos.
{73332}{73402}12, 11...
{73404}{73446}Dez...
{73448}{73506}nove, oito...
{73530}{73638}7, 6, 5,...
{73676}{73746}4, 3...
{73780}{73860}dois, um...
{73902}{73926}Zero.
{74038}{74074}Eu acho que ela estava certa.
{74322}{74372}A tora deve perfurar a urna.
{74500}{74548}Vamos lá!
{74590}{74658}Está perdendo força.|Jamais conseguirá.
{75860}{75916}Pura luz, fogo e água.
{78108}{78140}Pegue o relógio.
{78140}{78190}Entendi.
{85382}{85428}Parada aí mesmo!
{85520}{85568}Lara, desista.
{85594}{85642}Você vai atirar em mim, Alex?
{86914}{87008}Você sabe onde eu posso|fazer uma ligação internacional?
{87068}{87116}Meu telefone está molhado.
{87358}{87402}Sim?
{87404}{87442}Senhorita Croft, como vai?
{87444}{87484}Viva.
{87486}{87540}E na luta, eu espero.
{87542}{87592}- E você?|- Superlativo.
{87594}{87680}Mas é claro, Eu divago.|Você tem a minha metade do Triângulo.
{87682}{87734}E você tem|o relógio do meu pai.
{87736}{87814}Ouça, querida. Sem um ao outro|somos bastante inúteis neste momento.
{87814}{87882}Nós deveríamos reavaliar|nossas posições.
{87884}{87948}Gostando ou não,|você e eu estamos juntos neste negócio.
{87950}{87988}Deveríamos ter|uma reunião de negócios.
{87990}{88094}Você quer dizer que adoraria ter|outra oportunidade e tentar me matar.
{88096}{88160}Oh, que cruel.
{88162}{88242}Mas quem sabe.|Espere e veja.
{88242}{88316}Venha para Veneza,|Via Dolorosa.
{88318}{88378}Maravilhoso. Então tchau.
{88472}{88524}Mais forte.
{88600}{88652}Aí vem ele. Escondam-se todos.
{88654}{88718}Cuidado.|É algum tipo de máquina.
{88750}{88812}Bryce, sou eu.
{88814}{88902}- Alô?|- É Lara. Eu encontrei o templo.
{88904}{88964}- Me deparei com Sr. Powell.|- Você conseguiu pegar o relógio?
{88964}{89030}Não, mas eu peguei a primeira parte.
{89032}{89082}Oh, beleza, incrível.
{89084}{89150}Parece que estou na mesma|que o Sr. Powell.
{89152}{89202}- Agora ele não vai querer te matar?|- Não, seu bobo.
{89204}{89286}O problema dele é que ele precisa|da minha metade.
{89288}{89358}Até lá,|Sou sua nova melhor amiga.
{89360}{89418}E a outra metade?|O alinhamento final...
{89420}{89500}é em 66 horas e 53 minutos,|e ainda não temos nenhuma idéia...
{89502}{89564}de onde a segunda metade|está escondida.
{89566}{89626}Ele vai me contar|onde está a segunda metade.
{89628}{89648}Vai, é?
{89648}{89706}Bryce, acredite em mim.|Faça as malas para Veneza.
{89708}{89776}Malas pra onde? Alô? Lara?
{89846}{89874}Tchau então.
{90590}{90634}Beba.
{90712}{90742}Descanse.
{90786}{90834}Não há descanso|para a malvada.
{90836}{90916}Conseguiu o que veio buscar?
{90918}{90966}- Sim, consegui.|- Muito mal.
{90968}{91016}Mal para o mundo.
{91018}{91064}Agora o mundo está salvo.
{91092}{91170}Um pouquinho seguro,|talvez...
{91172}{91228}porque você continuará.
{91230}{91290}Seu pai disse que|você jamais desistirá.
{91292}{91376}Meu pai?|Você o conheceu?
{91406}{91438}Agora, beba.
{91438}{91482}Termine seu chá.
{91540}{91642}O gosto é muito ruim,|mas é bom para você.
{91642}{91678}Vê?
{92634}{92672}Boa noite.
{92752}{92806}Você está com os Illuminati.
{92888}{92918}Não entendi?
{92920}{93006}Eles não existem.|É só uma estória de ninar.
{93178}{93224}Illuminati...
{93250}{93296}O povo da luz.
{93356}{93402}Você trouxe meu Triângulo?
{93404}{93498}Não, claro que não trouxe.|Você escondeu em algum lugar.
{93564}{93612}Você pode ficar com|o Triângulo que você tem...
{93612}{93700}e eu ficarei com o relógio do seu pai,|e podemos ser parceiros.
{93702}{93740}Quem senta aqui?
{93800}{93852}Nós podemos ser parceiros|e tentaremos conseguir o grande prêmio.
{93854}{93908}O Triângulo da Luz.
{93910}{93990}Sim, mas quem senta aqui?
{93992}{94098}É um sonho inacreditável,|um temeroso poder.
{94100}{94146}Poderia consertar|tantos erros.
{94194}{94246}Eu não acho que você senta aqui,|senta?
{94500}{94544}Eu sento aqui...
{94592}{94648}Como se fosse na|mão direita de Deus,
{94696}{94724}Na verdade...
{94726}{94812}Eu agora sento exatamente|onde seu pai sentava.
{94918}{94962}Você está mentindo.
{95024}{95092}Não, ele foi meu mentor|na ordem.
{95128}{95174}Isso foi uma honra.
{95202}{95248}Eu não acredito em você.
{95286}{95322}Meu pai não andava|com os lluminati.
{95324}{95386}- Ele teria me dito.|- Ele escondia muitos segredos.
{95478}{95524}Não de mim.
{95526}{95578}Especialmente de você.
{95694}{95728}Eu sei o que você quer, Lara.
{95752}{95790}Oh, eu duvido.
{96020}{96100}Outra vida com seu pai,
{96102}{96158}uma segunda chance.
{96160}{96222}E estará ao alcance do meu|poder te dar.
{96250}{96342}O Triângulo concede|ao seu dono...
{96344}{96390}o poder de Deus,
{96390}{96510}de mover para trás e para frente|através do tempo, desfazer o passado.
{96540}{96636}Me ajude, e eu darei a você|o que eu sei que você quer...
{96638}{96718}ter seu pai|de volta para você.
{96810}{96882}E como saberei|se quando eu te entregar o Triângulo...
{96884}{96940}você não tentará|simplesmente me matar?
{97024}{97092}Isso tornaria tudo mais fácil|para você,
{97094}{97198}em solo mais familiar...|Se eu te matasse agora?
{97242}{97282}Você vai reconsiderar?
{98732}{98816}- Oi, Alex.|- Eu suponho que você ache...
{98816}{98862}que sou um mesquinho,|inescrupuloso em liquidação...
{98864}{98934}- e que faço qualquer coisa por dinheiro.|- Isso mesmo.
{98964}{99012}Bem, o dinheiro é verdade,|Eu acho.
{99134}{99182}Então é isso, Alex?
{99184}{99278}Se você cruzar meu caminho, não poderemos|mais ficar amigos.
{99392}{99444}Sempre um prazer.
{99518}{99564}Agora uma ducha fria.
{99566}{99618}Acho que temos um problemão.
{99620}{99676}- Segure isso, você pode?|- Obrigado.
{99676}{99754}Eles pensam que temos|a metade do triângulo de Lady Croft.
{99756}{99836}Sim. Eles acham que está nesta caixa|que você está carregando agora.
{99862}{99904}E é?
{99904}{99942}Porque você não se|preocupa com outra coisa?
{99944}{99992}Claro que não é.
{99994}{100094}Eu não entendo. Que chance de sucesso|temos sem isso?
{100096}{100156}Zero. Não insista.
{100158}{100196}Mas...
{100360}{100410}Que bela surpresa.
{100478}{100514}Obrigado.
{100578}{100648}Bom, hora de salvar o universo|de novo, não é?
{100648}{100684}Absolutamente.
{101512}{101596}Você tem certeza de que|ela é realmente necessária?
{101598}{101672}Bem, um caçador de tumbas|é bom. Dois, melhor.
{101884}{101966}Meu traseiro dormiu de novo,|toda a nádega esquerda.
{101968}{102036}Verdade?|Isso é fascinante.
{102180}{102228}- Quanto tempo?|- Algumas horas.
{102230}{102286}Nós teremos que andar|a última hora na terra.
{102292}{102370}Helicópteros não conseguem|voar perto da cidade em ruínas.
{102372}{102419}É uma zona morta.
{103438}{103484}Ficamos com todos os cachorros.
{103522}{103569}Muito dinheiro americano.
{103604}{103643}Todos os cachorros.
{104331}{104414}- Você vai para o Lago Gelado|- Sim
{104419}{104494}- Para a cratera?|- Sim. Para a cratera do meteoro.
{104494}{104604}Não vá. Você está arriscando tudo.|- Para vê-lo novamente.
{104638}{104684}Para ver quem?
{104694}{104728}Seu pai.
{106350}{106400}Bem-vindo à Zona Morta.
{106781}{106834}Isso não é um país.|É um cubo de gelo!
{106892}{106931}Vamos!
{109086}{109136}Isso aí. Vamos nessa.
{110412}{110462}Vai! Pega!!
{110622}{110656}Mas que coisa!
{110695}{110812}É uma tempestade temporal.|O tempo lá é ignorado.
{110812}{110902}Temos que encontrar o Olho!|Todos! Vamos!
{110907}{110984}Estamos correndo contra o tempo!|Vamos! Vamos!
{111442}{111476}Já começou.
{111550}{111619}Aposto 50 pratas que|a peça está dentro do sol.
{112648}{112760}Pelo amor de Deus, apressem-se! O eclipse vai terminar em poucos minutos!
{112948}{113010}Alex, me dê o relógio.|Eu sei o que fazer.
{114318}{114356}Ela pegou a peça?
{114592}{114631}Nós vamos agora...
{114632}{114688}unir estas duas partes,
{114690}{114795}o passado e o presente.
{114798}{114892}Finalmente,|nós do Illuminati...
{114893}{114964}iremos controlar o tempo e cumprir|a sagrada promessa...
{114966}{115024}para nossos antepassados.
{115024}{115150}- Breve, todo o mundo saudará...|- Chega dessa tagarelice.
{115257}{115306}Vamos! Vamos!
{115936}{116007}Não foi o que esperava,|Sr. Powell?
{116190}{116243}Eu tenho um palpite|sobre isso.
{116284}{116358}Apesar de tudo,|você é filha de um gênio.
{116360}{116416}Deixe-me testar minha teoria.
{117622}{117750}Você tem que deixar ele ir.|Chega de borbulhar.
{117752}{117796}Você me mostra como|completar o Triângulo...
{117798}{117846}podemos mudar este destino.
{117895}{117976}Se você me entregar o poder de Deus,|Eu posso poupá-lo.
{117978}{118024}É apenas um pequeno passeio|de volta no tempo.
{118069}{118160}Mas eu estou quase certo de que|você solucionou o problema.
{118208}{118288}E também, claro,|há a perda do seu pai.
{118290}{118348}Eu posso mudar aquilo.
{118664}{118710}É melhor você estar|preparado para isso.
{118840}{118934}- Desatache sua mira laser.|- Faça isso.
{119824}{119892}''para ver o mundo|num grão de areia.''
{120676}{120710}Papai?
{120928}{120974}Isso é real?
{121012}{121062}Isso é um cruzamento...
{121064}{121114}entre meu passado e seu presente.
{121143}{121194}Porque você não me contou|a respeito dos Illuminati?
{121195}{121245}Você era só uma criança.
{121252}{121298}Você poderia ter escrito|nos seus diários.
{121300}{121382}- Você nunca mencionou, nenhuma vez.|- Eu queria contar-lhe tudo.
{121384}{121448}Mas na ferocidade|das minhas próprias batalhas...
{121448}{121538}Eu me esforcei em dizer-lhe|apenas o que poderia inspirá-la...
{121540}{121576}e mantê-la segura.
{121600}{121645}Eu te amo tanto.
{121678}{121716}Mas eu sinto sua falta.
{121748}{121805}E eu sinto sua falta.
{121860}{121916}Eu sei porque você veio aqui...
{121916}{121998}porque você tirou o poder da luz,|mas isso não pode acontecer.
{122000}{122100}Porque? Porquê não podemos usar|o poder só desta vez??
{122131}{122172}Porque você não pode ficar?
{122172}{122266}Nós não podemos mudar o tempo.
{122268}{122338}Mas o tempo foi roubado de nós...
{122381}{122428}e isso não é justo.
{122428}{122506}Não, isso não é justo.
{122507}{122556}Mas você rouba o tempo|de você mesma...
{122558}{122654}e tem que devolver.
{122656}{122710}Você tem que destruir o Triângulo.
{122778}{122846}De repente me sinto tão sozinha.
{122848}{122984}Você jamais estará sozinha. Estou sempre com você|como sempre estive.
{125432}{125462}Mexam-se!
{125752}{125790}Espere!
{125819}{125862}Seu pai implorou pela sua vida...
{125864}{125914}quando pegamos ele nos traindo.
{125916}{125988}Ele implorou como uma criança.
{125990}{126019}Renda-se.
{126066}{126114}Nunca.
{126172}{126294}Ele pareceu especialmente preocupado|que eu não pegasse isso.
{126428}{126490}Lara, não!|O lugar está caindo!
{126492}{126564}- Isso é loucura!|- Tire todos daqui.
{126694}{126734}Se apresse.
{127016}{127058}Aí vamos nós,
{127060}{127110}sãos e salvos.
{127360}{127388}Sem armas.
{131655}{131708}Oh, meu Deus!
{131758}{131800}Quietinho.
{132592}{132618}O que?
