{828}{878}Nos filmes Drácula usa uma capa...
{878}{958}e algum inglês velho sempre consegue|salvar o dia no último minuto com...
{958}{1005}cruzes e água benta.
{1005}{1079}Mas todos sabem que os|filmes são pura lorota.
{1079}{1203}A verdade é que começou com|o Blade e terminou com ele.
{1203}{1270}O resto de nós só foi no embalo.
{1332}{1420}Deserto Sírio
{4387}{4420}O que são essas pegadas de galinha?
{4420}{4470}É Cuneiforme.
{4470}{4535}Tem uns 4000 anos.
{4535}{4589}Por que aqui?
{4589}{4651}Porque aqui é o berço da civilização.
{4700}{4744}Ele estaria confortável aqui.
{4744}{4808}Não sei, Dan, parece outra|perda de tempo.
{4808}{4851}Tem algo embaixo da gente.
{4852}{4899}Encontrou um relógio?
{4966}{4998}Isso é um corpo?
{5109}{5138}Pessoal.
{5344}{5427}Oh, Jesus Cristo. Que caralho|é esse! Fode-mãe!
{8767}{8831}Legendas: jmsilv@netscape.net|Re-Sync: SHDW
{9013}{9043}A ponte sobre a passagem.
{9043}{9117}Saquei. Indo para o oeste.|Estou em baixo de você.
{9143}{9165}Vá.
{12514}{12540}Está bem, senhor?
{12961}{12993}Ele está armado!
{13758}{13789}Isso é uma estaca de prata.
{13789}{13849}Por que não virou cinza?
{13849}{13914}Por que você não é mais esperto?
{13946}{14001}Não sou um vampiro,|seu merda retardado!
{14141}{14186}Foi uma cilada para você.
{14631}{14663}Caralho!
{15319}{15366}Oh, Blade.
{16270}{16306}Que porra aconteceu esta noite?
{16378}{16411}Como vou saber?
{16431}{16465}Ele era humano.
{16465}{16517}Está ficando descuidado, Blade.
{16517}{16565}Matar vampiros é limpeza.
{16565}{16634}Viram cinzas, não tem ambulâncias.
{16635}{16745}Matar humanos é sujeira, esperemos|que ninguém tenha te identificado.
{16769}{16810}Esse foi bom.
{16920}{16998}-O que é isso?|-Um novo sistema de liberação de seu soro.
{16998}{17143}Um inalador efervescente.|Morda e ele libera automaticamente.
{17143}{17182}Uns amigos meus o fizeram.
{17182}{17223}Amigos!?
{17224}{17301}Sim. Lembra o que é?
{17301}{17338}Foi horrível.
{17338}{17430}Um carro bateu e o cara de casaco|estava atirando no outro cara.
{17430}{17471}Havia muito sangue.
{17471}{17546}Obrigada. Essa foi só uma amostra|da desordem que aconteceu...
{17546}{17630}durante o ousado tiroteio desta noite|que deixou pelo menos 4 pessoas mortas.
{17630}{17729}Aparentemente um cidadão|anônimo filmou tudo.
{17729}{17804}-Ei, Ray. Temos uma pista.|-Vamos pegar um avião, Wilson.
{17804}{17855}Chegou à hora de pegar esses caubóis.
{17855}{17914}É isso ai!
{18717}{18763}O que ele anda fazendo?
{18763}{18854}Cacete! Toda essa chupação.|Já chupou 5.
{18854}{18920}-Acha que temos segurança suficiente?|-Ele não foi capturado.
{18920}{19027}Ele nos permitiu trazê-lo, entendeu?|Vou entrar.
{20698}{20740}Não deviam ter me acordado.
{20740}{20792}Não tivemos escolha.
{20906}{21009}Seu sangue... Seu sacramento...|pode nos libertar agora.
{21009}{21094}O que te faz pensar|que me importo?
{21094}{21152}-Seu povo precisa de você.|-Meu povo?!
{21240}{21327}Não passam de sombras|comparados ao que eram.
{21327}{21386}Olha o quanto caíram.
{21386}{21443}O mundo é diferente do da sua época.
{21443}{21547}Os humanos têm um|novo caçador...Blade!
{21547}{21628}E gostaria que eu o matasse, não é?
{21628}{21668}Sim.
{21737}{21790}Psicopata armado foi filmado.
{21790}{21834}Só isso?
{21834}{21898}Esse também.
{21949}{22017}Esse fodidão precisa de outro hobby.
{22017}{22083}Esperemos que não.
{22355}{22426}-O vigiado está indo para o oeste.|-Entendido.
{22498}{22699}Esta noite o Dr Edgar Vance, psiquiatra criminal e|autor do Best Seller do New York Times:
{22699}{22800}Saúde humana: A Descoberta do Ser Integral.
{22800}{22881}Também conosco, Martin Vreede,|Chefe de Policia.
{22881}{22972}Estarão conosco por uma hora|e responderão as suas ligações.
{22972}{23058}Em seguida no Bentley Tittles ao vivo.
{23058}{23185}Ok. Chefe Vreede, o que tem|a dizer sobre esses rumores...
{23185}{23235}que estamos ouvindo|sobre vampiros.
{23235}{23315}Se vampiros existissem, não acha que já|os teríamos achado?
{23315}{23355}O povo não devia se|incomodar com isso.
{23355}{23434}Deviam se concentrar em sujeitos|como esse criminoso: Blade.
{23434}{23519}É sobre esse sujeito que quero ouvir.|Quero ouvir sobre o Blade.
{23519}{23591}-O que tem ele?|-Ele é o psicopata que estamos atrás.
{23591}{23683}Blade é um individuo perturbado,
{23683}{23711}Minha compreensão é...
{23711}{23803}que ele crê que há uma enorme|conspiração dos vampiros.
{23856}{23887}E eles estão entre nós.
{23887}{23985}Você tem que examinar a base psiquiátrica|de uma crença como essa.
{24021}{24113}Parabéns. Você é famoso.|Alguém nos pegou.
{24113}{24216}Seu rosto está em todos os jornais, na TV,|a mídia está fazendo um carnaval.
{24217}{24265}-Como se eu me importasse.|-Pois devia.
{24265}{24345}Algo assim. Apagar um humano.
{24345}{24475}Na opinião de todo o mundo, você|é o inimigo público número um.
{24475}{24534}Não sabia que estava num|concurso de popularidade.
{24566}{24633}Cacete, Blade! Não vê o que estão fazendo?
{24633}{24710}Estão fazendo uma campanha|de relações públicas.
{24710}{24796}Agora não precisamos nos|preocupar "só" com vampiros,
{24796}{24865}agora é o resto do mundo também.
{24915}{24976}Você se preocupa demais, velhote.
{24976}{25037}E é por isso que ainda|estamos vivos, caralho!
{25037}{25129}Estou fazendo isso desde|antes de você nascer, Blade.
{25129}{25170}Você é como um filho para mim.
{25170}{25238}Sinto ter ficado velho
{25238}{25317}Imagino você sozinho,|cercado de inimigos,
{25317}{25369}e isso estraçalha meu coração.
{25409}{25459}Não podemos ganhar|essa guerra sozinhos.
{25526}{25562}É isso ai!
{25562}{25607}Bebê a bordo.
{25607}{25691}Olha só. Parece que ganhamos|uma refeição com mistura.
{26054}{26113}Vem cá, gatinha.
{27280}{27376}-É isso ai, cambada!|-O que temos pro jantar!
{27706}{27732}Ei, belezoca.
{27913}{28028}Não!
{28093}{28147}Grite se doer, mocinha.
{28272}{28297}Foda-se?
{28394}{28425}Alho!
{29065}{29096}Vem!
{29929}{29982}Grite se doer, mocinha.
{31624}{31653}O que é?
{31678}{31719}Está preocupado com o quê?
{32139}{32170}Vamos!
{32743}{32783}Rotina de proteção de dados habilitada.
{33014}{33066}Estação de trabalho 1 proteção habilitada...
{34551}{34583}Mexa um dedo e está morto!
{34583}{34624}Que tal este?
{34624}{34693}-Ele tem algo na mão!|-Se arranca, Blade!
{34851}{34877}Puta que pariu!
{35254}{35313}O que está acontecendo ai?|Alguém fale comigo.
{35484}{35548}Parado ai. Não atirem!
{36389}{36439}DEPARTAMENTO DE POLICIA.
{36668}{36731}Levanta pra cuspir, dorminhoco.
{36846}{36922}Agente Especial Ray Cumberland,|Wilson Hale, FBI.
{36922}{36978}Estamos atrás de você|há muito tempo.
{37008}{37061}-Whistler?|-Morto?
{37122}{37156}Como todas as suas vitimas.
{37201}{37245}Diz ai, quantas pessoas|você matou, Blade?
{37245}{37296}30, 40, 50?
{37296}{37379}1182
{37379}{37446}Mas todos eles eram familiares:
{37446}{37503}gente que trabalha com eles.
{37503}{37596}E esses "eles" são vampiros, certo?
{37723}{37802}Pode ficar com esse papo furado|o tempo que quiser, Blade.
{37802}{37850}Isso não cola.
{37850}{37888}Sabemos o que você é.
{37910}{37998}-Um assassino frio e calculista.|-E um filho da puta doentio.
{37998}{38051}Deixemos o diagnostico|para profissionais.
{38094}{38171}Oi, Blade, meu nome é Dr Vance.
{38171}{38248}Estou aqui para fazer|uma avaliação psiquiátrica.
{38290}{38360}Senhores. Se importariam de nos|dar uns dois minutos a sós?
{38385}{38418}Ele é todo seu.
{38713}{38768}Sei que isso deve ser|muito assustador para você.
{38768}{38831}Quero que saiba que|estou aqui para ajudar.
{38831}{38967}Mas para isso, tenho que lhe|fazer algumas perguntas. Ok?
{39031}{39065}Pode dizer que dia é hoje?
{39173}{39250}E o presidente? Sabe quem|está na Casa Branca agora?
{39250}{39290}Um cuzão.
{39406}{39426}Ok.
{39426}{39466}Vamos falar sobre...
{39466}{39511}Vampiros!
{39511}{39562}O que pode me dizer sobre eles?
{39633}{39668}Eles existem!
{39687}{39726}Você é um?
{39821}{40001}E o sangue? Quando você o bebe,|se sente sexualmente estimulado?
{40088}{40177}É que, me parece que vampirismo...
{40177}{40257}tem fortes conotações|com confusão sexual.
{40257}{40350}Troca de fluidos corporais.|Esse tipo de coisa.
{40350}{40404}Você tem que se perguntar:|Qual a origem disso?
{40454}{40539}E me questiono como era|sua relação com sua mãe.
{40642}{40683}Vocês eram muito íntimos?
{40765}{40790}Jesus!
{40884}{40925}-Ele é psicótico!|-Grande novidade.
{40925}{40960}Para sua segurança e a do público,
{40960}{41008}recomendo que seja transferido|imediatamente para uma prisão psiquiátrica...
{41008}{41066}Quero que isso se foda!|Esse Homem é meu prisioneiro!
{41066}{41122}Ele é está sendo procurado pela sua|ligação com uma enorme lista de crimes federais.
{41122}{41146}Esperem, senhores.
{41146}{41179}Estamos na minha jurisdição.
{41179}{41235}Se não gostarem falem|com o magistrado local.
{41235}{41314}Esse homem é meu prisioneiro,|não foda meu negócio.
{41314}{41384}Uma equipe do hospital está|cuidando da transferência.
{41384}{41451}-Pensei que era nosso parceiro nisso.|-Desta vez não.
{41591}{41670}Isso é para deixar você sossegado.
{41729}{41831}A dose normal é 200, 300|miligramas, mas acho que...
{41831}{41910}Um híbrido grandão e fortão como você...
{41910}{41968}vai precisar de uns 2000.
{41968}{42037}Não tem problemas|com agulhas, tem?
{42104}{42168}Pronto. Não foi tão ruim, foi?
{42238}{42272}Você está fraco
{42272}{42384}Deve ser duro para você.
{42434}{42562}Quem imaginaria que um mero humano|como eu podia subjugar você.
{42616}{42667}Você é um deles...
{42719}{42755}um familiar.
{42845}{42882}Há quatro anos.
{42992}{43032}Fim do jogo, Blade.
{43032}{43102}Os planos deles estão se concretizando.
{43102}{43221}Por que não relaxa e curte o show?
{43398}{43482}Odeio familiares!
{43727}{43775}É por isso que ainda estamos vivos, caralho!
{43775}{43838}Você é como um filho para mim.
{43909}{43994}Desculpe ter envelhecido.
{44042}{44188}Imaginá-lo sozinho, cercado de inimigos,|estraçalha meu coração.
{44824}{44853}Oi, Blade.
{44853}{44889}Fico feliz de finalmente te conhecer.
{44890}{44936}Sou uma tremenda fã.
{44936}{45007}Gostei das suas tatuagens,
{45046}{45079}significam algo?
{45163}{45192}Você está bem?
{45192}{45231}Está cansado?
{45293}{45326}Está fraco?
{45427}{45536}Movemos os humanos,|como peças de xadrez,
{45537}{45658}Os usamos para tirá-lo da sua toca.
{45890}{45922}Você não é tão grande.
{45973}{46016}Está completamente só, Blade.
{46016}{46078}Ninguém vai te ajudar agora.
{46536}{46562}Foda-se.
{46597}{46608}Boa noite, senhoras.
{46608}{46652}Hannibal King!
{46755}{46791}Acorde, Blade!|Esta sendo resgatado.
{47951}{47985}Vá!
{49495}{49526}Whistler!
{49555}{49586}Por aqui!
{49791}{49837}Blade! Você está morto!
{49886}{49910}Abaixem-se!
{50075}{50097}Blade!
{50311}{50337}Onde está indo?
{50337}{50373}Onde diabos eles está indo!?
{50373}{50424}Isso é pra ser um resgate!
{50590}{50608}Voltem!
{50686}{50710}Estamos encurralados!
{50710}{50764}-Não consigo atirar em volta de cantos.|-Eu consigo.
{52291}{52340}Ok. Estamos fodidos.
{52340}{52380}Estamos numa boa.
{52675}{52732}Esqueci minha espada.
{52980}{53007}Vamos!
{53353}{53371}Gabby?
{53547}{53570}Pegamos.
{53570}{53612}Chegaremos logo.
{53612}{53653}Quem diabos são vocês?
{53653}{53716}Bem, meu nome é Hannibal King
{53716}{53778}e a gata infernal|é a Abigail.
{53806}{53835}A filha de Whistler.
{54151}{54196}Achei que os vampiros tinham|matado a família de Whistler.
{54196}{54232}E mataram.
{54243}{54278}Nasci depois. Filha de uma amasia.
{54345}{54368}Quando fiquei maior de idade,
{54368}{54427}localizei meu pai e disse|que queria entrar na jogada.
{54427}{54474}Venho fazendo isso desde então.
{54645}{54700}Bem-vindo a colméia.|Nosso esconderijo.
{54700}{54768}Como você banca essa operação?
{54768}{54806}Trepei com um monte de velhotes.
{54851}{54892}Vamos, cara, estou brincando.
{54892}{54929}Você conheceu o Jax.
{54929}{55032}Esse é Hedgis. Summerfield.|Ela fez seu inalador de soro.
{55032}{55162}Aquela pivete que acabou de ver|é a filha de Summerfield: Zoey.
{55215}{55252}A gente se chama|“Caçadores Noturnos"
{55252}{55355}Parece um nome rejeitado|pelos desenhos animados.
{55355}{55448}Ia ser "Ursinhos Carinhosos",|mas já pegaram o nome.
{55535}{55570}Vocês são em quanto?
{55570}{55594}O suficiente.
{55594}{55636}Operamos com células de revezamento...
{55636}{55692}Quando uma célula cai,|outra entra em ação.
{55692}{55751}Somos reforços.
{55805}{55849}Vocês amadores é que vão me ajudar?
{55916}{55940}Vocês?
{55940}{56029}Olhem-se no espelho.|Vocês são crianças!
{56029}{56084}Não estão prontos para isso.
{56084}{56142}Olha o jeito que se vestem?
{56180}{56217}Dando uma de unidade tática?
{56217}{56293}O que é isso? "Foda-se"
{56293}{56327}Uma piada.
{56327}{56398}Qual é a de vocês?|Acham que isso é piada?
{56398}{56474}Acham que isso é|uma comédia de tv?
{56474}{56540}Em primeiro lugar, não|seja mal educado.
{56540}{56629}Em segundo, tenho certeza|que salvamos sua bunda.
{56695}{56723}Estou impressionado.
{56724}{56809}Olhe, Blade. Meu pai queria|que o ajudássemos.
{56809}{56883}Goste ou não. Somos|tudo que você tem.
{56883}{56968}O que os faz achar|que sabem caçar vampiros?
{56968}{57044}Bem, pra começo de conversa,
{57066}{57102}eu era um.
{57102}{57174}Passei no teste?
{57226}{57255}Novatos.
{57255}{57323}Hannibal King: filho de|uma égua rampeira!
{57323}{57409}Eu devia ter arrancando seu coração|sangrento quando tive a chance.
{57604}{57674}O Blade era nosso.|Era nosso!
{57729}{57788}E não esfregue na minha|cara que me disse, Asher.
{57788}{57849}Qual o problema, golinho,|quer uma folguinha?
{57849}{57879}Vá se foder.
{57912}{57954}Fomos pegos sem as calças.|Desprevenidos.
{57954}{57994}Sem as calças?
{57994}{58079}Eles praticamente|comeram nossos cus
{58079}{58111}Oh, você adorou.
{58111}{58154}Ele foi informado?
{58154}{58206}Sobre o fracasso de vocês?
{58248}{58271}Sim.
{58322}{58366}Talvez esteja na hora|de eu entrar no jogo.
{58532}{58619}Sabe aquele tipo de mulher que|você sabe que só vai dar encrenca?
{58619}{58708}Você a vê e todos os alarmes no seu|cérebro começam a soar um a um.
{58708}{58781}Mas mesmo assim, você|pede o telefone dela.
{58781}{58850}Esse é o tipo de mulher|que eu sempre arranjo.
{58850}{58895}Mas essa fulana...
{58950}{59019}Na loteria das vagabundas filhas da puta,|ela ganhou o primeiro premio.
{59019}{59071}Seu nome é Danica Talos,
{59071}{59113}você a conheceu mais cedo,
{59113}{59202}Diferente dos outros vampiros,|seus caninos ficam na sua vagina.
{59268}{59295}Seguindo em frente...
{59295}{59371}O homem à esquerda,|é o irmão dela, Asher...
{59372}{59448}E essa fralda suja ambulante|é Jarko Grimwood.
{59448}{59499}Ganhei a Danica num bar...
{59499}{59601}e passei os próximos 5 anos brincando de|esconde e chupa como seu criadinho de piscina.
{59632}{59674}Eventualmente, a Abigail me encontrou...
{59674}{59730}Summerfield me deu a cura...
{59730}{59770}e agora eu os mato.
{59770}{59860}E isso transformou uma|careta em um sorriso.
{59923}{59977}Precisamos juntar|nossos recursos, Blade.
{59977}{60010}"Nós?"
{60074}{60104}Sim...Nós.
{60104}{60148}Ele voltou.
{60230}{60252}Dê uma olhada.
{60264}{60315}A tumba de Drácula|Senhor dos Vampiros.
{60386}{60418}Está zoando com minha cara.
{60531}{60558}Ele é de verdade, Blade.
{60558}{60599}Esse é um pedaço de sua armadura.
{60599}{60716}Extrapolamos e chegamos a uma idéia básica|da aparência desse fode-fode. Dê uma olhada.
{60716}{60799}Drácula é apenas um dos|nomes que ele usou.
{60799}{60871}Os babilônios o adoravam como Dagon.
{60871}{60911}E agora ele é chamado de Drake.
{60911}{60998}Se acreditar nas lendas, ele|nasceu na antiga Suméria.
{61212}{61309}Ninguém conhece os detalhes de sua origem,|mas sabemos uma coisa na certa.
{61398}{61435}Ele foi o primeiro da sua espécie.
{61455}{61488}O patriarca...
{61488}{61536}do Homo Nocturnus.
{61675}{61720}Ele nasceu perfeito.
{61804}{61851}E igual ao grande tubarão branco...
{61851}{61915}Esse cara nunca precisou evoluir.
{61915}{62017}Esqueça os filmes, os livros,|com ele não tem final feliz.
{62076}{62232}La estava ele, nos bastidores, abrindo uma trilha|sangrenta eras afora, quando subitamente...
{62297}{62329}sem mais nem menos...
{62430}{62459}ele sumiu.
{62459}{62514}Ai ouvimos um zum zum zum
{62514}{62555}Os vampiros o estavam procurando.
{62555}{62626}Alguns dizem que ele estava|dormindo há séculos...
{62626}{62698}que tinha se isolado de um mundo|que passou a lhe causar nojo.
{62698}{62805}E de acordo com nossa informação, ele|foi achado no Iraque uns 6 meses atrás.
{62805}{62849}E ele ficou puto pra caralho.
{64226}{64251}Na vitrina...
{64251}{64325}vocês vendem produtos|com o tema vampírico.
{64395}{64412}Sim.
{64412}{64449}Dê uma olhada.
{64449}{64489}Talvez tenhamos algumas coisas.
{64566}{64630}Temos lancheiras Drácula.|Você viu?
{64630}{64724}Cabecinhas do Drácula, chaveiros,
{64724}{64797}Temos praticamente de tudo...
{64797}{64868}Até vibradores vampiros.
{64975}{65031}Quer algo em especial?
{65090}{65116}Ei, cara,
{65116}{65161}ela esta falando com você.
{65359}{65377}O quê?
{65377}{65425}Quer me beijar, bonitão.
{66182}{66211}Por que acordar o Drake agora?
{66211}{66268}É exatamente isso que|queremos entender.
{66268}{66311}Quando eu tinha minhas presas,
{66311}{66386}eles costumavam falar sobre|uma solução final dos vampiros.
{66386}{66466}Mas nunca consegui entender por que iriam|destruir sua fonte de alimentação?
{66466}{66498}Isso não faz sentido, certo?
{66498}{66547}Eles sempre tiveram planos|para a raça humana.
{66547}{66600}E parece provavel que o que quer|que estejam tramando,
{66600}{66652}À volta do Drake faz|parte dessa trama.
{66652}{66672}Encaremos os fatos,
{66672}{66721}estamos numa luta|destinada a derrota.
{66721}{66788}A gente mata 100 deles|por ano, grande coisa,
{66788}{66854}Ha milhares deles, talvez|dezenas de milhares.
{66854}{66917}-Precisamos de uma nova tática.|-Tipo?
{66917}{66958}Uma arma biológica.
{67002}{67038}Para vocês que não são cegos,
{67095}{67139}vamos a uma apresentação|audiovisual.
{67139}{67223}No último ano estive trabalhando|em DNA sintetizado...
{67223}{67301}para criar um vírus artificial|especifico para vampiros.
{67329}{67358}Seu nome é “Estrela Diurna"
{67358}{67399}Pense só, Blade,
{67399}{67472}Podemos acabar com todos|eles numa cartada só.
{67472}{67522}E por que não|fizeram isso ainda?
{67522}{67579}O DNA não é puro o suficiente.
{67579}{67646}Resumindo. Precisamos de|um DNA mais puro.
{67685}{67724}Precisamos do sangue do Drácula.
{67724}{67843}Já que o Drácula é o progenitor da raça|vampírica, seu DNA ainda é puro.
{67843}{67960}Ele não foi diluído por centenas de|gerações de mutações seletivas.
{67960}{67999}Se tivermos seu sangue...
{67999}{68094}podemos tornar o vírus 100% eficiente.
{68094}{68146}Todos os vampiros vão|pra casa do caralho.
{68194}{68320}E ai? Vai entrar no clube e ganhar um|anel secreto dos "Caçadores Noturnos"?
{68499}{68523}Puta merda.
{68523}{68579}Senhores e tesuda.
{68579}{68609}Hoje Temos...
{68609}{68697}um belo sortimento de equipamentos|para botar para foder. Para seu prazer.
{68697}{68728}Arma eletrônica.
{68728}{68784}Vários calibres.
{68824}{68849}Munições explosivas.
{68849}{68946}Com uma carga de luz ultra|violeta ao invés do normal.
{68946}{68990}Eu as chamo de|"cães solares" Sun dogs.
{68990}{69057}Hedgis. Super cístico, fofinho.
{69144}{69250}Essa espingardinha é uma versão modificada|das armas individuais de combate do exercito...
{69250}{69341}Escolha seu veneno a gosto. Sun dog,|estacas, teleguiados,
{69341}{69420}Basicamente a que te der mais tesão,|vai arregaçar eles,
{69420}{69545}Mas claro. Elas não tem o|alcance de uma espada, mas...
{69545}{69567}Oh, meu Deus.
{69567}{69714}Aqui temos o que chamamos de Arco UV.
{69714}{69826}Os dois pontos são conectados|a um poderoso laser UV,
{69826}{69859}deixa comigo.
{69927}{70029}Essa malvadeza pode atravessar vampiros|como uma faca na manteiga.
{70029}{70124}Ainda estamos tentando distinguir|fato da ficção sobre o Drácula.
{70124}{70182}Virar nevoeiro duvido....
{70182}{70260}Mudar a forma, talvez...
{70260}{70352}Não virar um morcego|ou lobo ou algo assim...
{70352}{70433}Mas um ser humano, podia ser possível.
{70433}{70530}Porque ele não teria uma|estrutura óssea normal,
{70530}{70611}seria mais como a de uma cobra,|com milhares de ossinhos...
{70612}{70742}Tenho uma perguntinha, Hedgis.|Você já trepou alguma vez?
{70762}{70832}Muitas vezes. Com moças.
{70859}{70911}Hora de uma pressão.
{70911}{71050}O elo mais fraco na cadeia de|comando dos vampiros são os familiares.
{71050}{71161}Os vampiros não podem sair de dia, então|usam humanos para seus trabalhos sujos.
{71161}{71286}A gente sangra os que querem ser vampiros,|e eles nos levam ao que interessa.
{71311}{71376}Um carrinho novo, tome muito cuidado.
{71551}{71587}Ela está fazendo uma lista de músicas...
{71587}{71651}ela gosta de ouvir mp3s|enquanto caça.
{71651}{71799}Para se distrair, Dark Core, trip hop, seja|la o que as molecadas ouvem hoje.
{71832}{71889}Sou mais fã do David Husselhof.
{73232}{73282}No final você sabe que sua|cabeça vai pular fora.
{73282}{73344}Caralho! Não! Por favor.
{73344}{73421}-Quem é teu supervisor|-Não conheço a porra do meu supervisor.
{73421}{73503}Juro! Juro! Puta que|pariu! Por favor.
{73638}{73711}Oh, é o seu? Eu fico com ele.
{73742}{73780}Vamos!
{73897}{73996}Alô?
{73996}{74048}Este é o Dr Vance,|você me bipou.
{74089}{74180}-É pra você. Vá em frente.|-Alô?
{74265}{74364}Sabe, um dia, você devia|sentar-se com alguém,
{74364}{74409}compartilhar umas coisas,
{74409}{74497}relaxar, entrar em contato|com sua criança interna, esse tipo de coisa,
{74497}{74610}E também, você devia piscar|de vez em quando.
{74731}{74814}Desculpe, consumi muito açúcar hoje.
{75248}{75305}Não pode ir entrando aqui desse jeito.
{75517}{75542}Com licença, senhor.
{75702}{75734}Não faça isso.
{76161}{76178}Onde está o Vance?
{76178}{76218}Sinto muito, mas não pode|ver o Dr Vance no momento.
{76452}{76480}Sente-se!
{76594}{76629}Pois não?
{76629}{76682}Lembra-se de mim?|Hora de dar o troco.
{76682}{76737}Ok, Vance, que caralho de|informação você está a par.
{76806}{76891}Jesus, é ele. Abby, é o Drake.
{77274}{77298}Então...
{77298}{77344}Você é o caçador que todos temem.
{77344}{77380}Tive um pressentimento|sobre você.
{77380}{77433}-Atire nele.|-Vá em frente, Blade.
{77433}{77480}Mostre se é bom mesmo.
{79651}{79703}Oh, meu Deus!
{79703}{79750}Ele levou meu bebê!
{79804}{79841}Meu bebê!
{81259}{81305}Cuidado. Andarilho Diurno.
{81305}{81412}Fiquei sabendo da sua|fraqueza por humanos.
{81412}{81456}Por que matou o Vance?
{81456}{81496}Não tinha mais propósito para ele.
{81496}{81545}Sua morte foi boa.
{81545}{81598}Rápida, limpa.
{81598}{81654}Não sei se isso existe.
{81654}{81685}Vai saber.
{81730}{81778}Como consegue sobreviver|a luz do dia?
{81778}{81838}Não leu a fábula de Stoker?
{81838}{81929}Fui o primeiro vampiro.
{81970}{82003}Sou único.
{82003}{82053}Então foi por isso que te|trouxeram de volta.
{82053}{82079}Claro.
{82079}{82155}Eles crêem que através de mim,|podem tornar-se Andarilhos Diurnos.
{82295}{82328}Olhe eles lá embaixo.
{82328}{82383}Rastejando como insetos.
{82414}{82492}Não sabem nada sobre honra|ou viver pela espada.
{82492}{82533}Não como eu e você.
{82568}{82631}Acha que fazem idéia do|que seja ser imortal?
{82631}{82663}Você não é imortal.
{82663}{82769}Já ouvi centenas de roedores como|você fazerem a mesma afirmação.
{82769}{82850}E todos acabaram na|ponta de minha espada.
{82850}{82898}Talvez eu também acabe|na ponta da sua.
{82898}{82991}Mas creio que é mais provavel que na|próxima vez que nos encontremos...
{82991}{83052}Você estará na ponta da minha.
{83053}{83091}Pegue!
{83639}{83695}Você viu o cara? Vamos perder.
{83736}{83810}Deus! Vamos perder, caralho.
{83878}{83905}O que é isso? O que está fazendo?
{83905}{83966}É uma proteína elástica, ok?|Vai parar a hemorragia.
{84016}{84043}Vai doer?
{84043}{84103}-Vai arder um pouco.|-Mesmo?
{84175}{84237}Vá tomar no cu!
{84348}{84384}já tive uma família...
{84384}{84457}Mulher, duas filhas...
{84573}{84628}Um vagabundo apareceu uma noite...
{84628}{84682}Um vampiro...
{84729}{84767}Ele brincou com elas primeiro
{84827}{84918}Forçando-me a decidir em|que ordem morreriam.
{84958}{84999}Estou nisso há muito tempo.
{84999}{85048}Bem antes de você nascer.
{85089}{85139}Não quero essa vida pra você, Abby.
{86166}{86196}Ei, Blade.
{86196}{86246}Uma pergunta para você:
{86246}{86326}Digamos que tenhamos êxito...digamos|que acabemos com todos os vampiros.
{86326}{86360}E depois?
{86396}{86426}Já se perguntou isso?
{86426}{86593}De alguma forma, não consigo|imaginar você ensinando karate na ACM.
{86865}{86939}-Ele me odeia, não é?|-Sim.
{87314}{87346}Por que faz isso?
{87346}{87461}Porque tenho algo ruim|dentro de mim.
{87512}{87552}Isto faz com que não saia.
{87552}{87609}Porque não é legal?
{87742}{87785}Porque o mundo não é legal.
{87939}{87983}Descobri onde os vampiros|estão trabalhando...
{87983}{88028}Empresas Biomedica
{88028}{88091}Estão comprando todo tipo de suprimentos.
{88091}{88130}Olhem só.
{88171}{88349}suplemento de crescimento de medula óssea,|enzimas de seqüência genética,
{88378}{88486}-Quer um bom para festa?|-O sortudo 7. Balas cheia de prata.
{88486}{88510}Feito.
{89243}{89270}Queria me ver?
{89270}{89317}Estamos encrencados.
{89317}{89377}Fazendo um bico, chefe?
{89377}{89418}Bosta!
{89714}{89739}O que está fazendo aqui?
{89739}{89778}Fale!
{89827}{89855}Fale!
{89945}{89956}Desembucha!
{89967}{89994}Você sabe o que estamos fazendo.
{89994}{90045}O que tem ai dentro?
{90249}{90298}O que está atrás da porta numero 1?
{90359}{90401}Não posso contar. Eles vão me matar.
{90401}{90447}Matar você Seu fode-mãe.|Eu te mato!
{90447}{90482}Só vou desfrutar mais.
{90698}{90729}Você sabe a rotina.
{91139}{91170}Luzes.
{91242}{91271}Deus do céu!
{91653}{91688}Que lugar é esse?
{91723}{91762}Uma fabrica de coleta de sangue.
{91910}{92035}Os vampiros decidiram que caçar|humanos um a um era muito ineficiente.
{92076}{92140}Por que matá-los se podem|ser mantidos vivos?
{92218}{92326}Em condições ótimas um doador pode|gerar de 25 a 50 litros de sangue.
{92352}{92387}Produtivo.
{92429}{92462}Onde pega toda essa gente?
{92462}{92568}Eles tem centros de triagem|nas maiores cidades...
{92568}{92705}Em uma dada hora, deve haver 2 ou 3 milhões|de indigentes circulando pelos EUA.
{92705}{92758}É só Pegá-los das ruas.
{92811}{92847}Ninguém se importa com eles.
{92888}{92942}Estamos fazendo um favor|para esse pais, na verdade.
{93011}{93057}A última solução dos vampiros.
{93087}{93120}Eles estão conscientes?
{93154}{93189}Eles sentem algo?
{93189}{93291}Estão num coma induzido, seus|cérebros estão mortos.
{93391}{93417}Olhe para isso.
{93417}{93468}Esse é o futuro que você quer?
{93468}{93581}Acha que têm um lugar para|você no futuro deles?
{93581}{93634}Não temos escolha.
{93668}{93726}Vão vencer. Não percebe?
{93726}{93815}Ele voltou e nada vai impedi-lo agora.
{93815}{93852}Tem a gente!
{93870}{93902}Vá!
{93956}{93987}Você tem 20 segundos.
{94065}{94097}vinte.
{94267}{94313}Qual é a senha de desligamento?
{94313}{94354}Colheita.
{94391}{94430}Digite a senha.
{94795}{94822}Vamos!
{95262}{95416}O rei dos gnomos, nunca tendo tentado|ser bom, era muito ruim.
{95416}{95514}Tendo decidido conquistar a Terra de Oz...
{95768}{95809}Isso não é videogame.
{96594}{96621}Cara...
{96621}{96663}Você está morto.
{96847}{96891}Mãe, a luz está esquisita.
{96945}{97007}-Como assim?|-Estão ligando e desligando.
{97097}{97130}Pessoal?!
{97171}{97275}Zoey, quero que vá se esconder, ok?|Como conversamos.
{97275}{97311}Vá.
{101095}{101139}Algo não está certo.
{102842}{102870}Zoe?
{103070}{103095}Whistler!
{103897}{104111}A mortalidade só chega aos|que foram feitos para ela.
{104923}{104951}Use a dor!
{105021}{105048}Use a dor!
{105151}{105180}Use a dor!
{105837}{105892}Jesus...Cristo!
{105918}{105964}Puta que pariu!
{105964}{106000}Bom cachorro.
{106000}{106048}Puta que pariu!
{106141}{106176}Seu nome é Packman.
{106176}{106253}Estamos enfiando o genes|vampiro em outras espécies.
{106253}{106293}Fazendo experiências.
{106293}{106376}Fizeram uma caralho de um|pomerânio vampiro?
{106423}{106445}Sim.
{106583}{106621}Precioso, não é?
{106621}{106651}Depende a quem perguntar,
{106651}{106729}porque claramente, esse cachorro|tem um pinto maior que o seu.
{106729}{106844}E quando, caralho, você viu|meu pinto, cara de cu.
{106940}{106986}Eu estava falando com ela!
{107079}{107115}Pobre King.
{107143}{107221}Você parece tão atormentado!
{107329}{107360}Pega aquela cadeira.
{107600}{107723}Você está meio insípido, amor, está|consumindo acido suficiente?
{107723}{107836}Já tentou truta, cavala...
{107836}{107973}Que tal pegar açúcar de confeiteiro,|colocar no meu pinto, e enfiá-lo na sua xoxota?
{107973}{108087}E que tal todo mundo parar|de falar a palavra pinto?
{108087}{108161}Isso causa minha inveja.
{108342}{108394}Fale-nos sobre o Blade, King.
{108394}{108454}Que arma é essa que ele está planejando?
{108454}{108523}Posso lhe dizer duas coisas:
{108564}{108705}Uma: Seu penteado está ridículo.
{108705}{108853}Dois: Comi muito alho|e acabei de bufar.
{108853}{108899}Bufa silenciosa,|mas mortal.
{108938}{108994}Desembucha, sua bicha louca.
{108994}{109060}Ok. Conte a você sobre a arma.
{109265}{109348}É uma formula nova, mais gostoso que|chocolate, metade das calorias,
{109348}{109386}Previne caries-
{109624}{109652}Você tem coragem, King.
{109652}{109695}Admito.
{109695}{109809}Mas por baixo de toda essa fanfarronice,
{109809}{109988}Eu sei o que teme, o que te|magoaria mais que tudo,
{110322}{110425}Não quer voltar a ser|um de nós, quer?
{110629}{110721}Vou te morder de novo, King.
{110721}{110839}E vou deixar você aqui|enquanto se transforma...
{110839}{111044}Vou te observar dia a dia enquanto|a sede aumenta cada vez mais...
{111101}{111246}E então, quando não agüentar mais...
{111370}{111425}Vou trazer a garotinha pra cá...
{111471}{111513}pra você se alimentar...
{111560}{111600}Gostaria, King?
{111655}{111713}Gostaria de tirar a vida dela?
{112108}{112156}Agora estamos chegando|a algum lugar, meu bichinho.
{112686}{112713}Você está bem?
{112754}{112787}Sim, vou ficar bem.
{112872}{112909}Não deixe que entre|nas suas entranhas.
{112973}{113009}Já aconteceu.
{114440}{114474}Ele é um dos nossos.
{114474}{114562}Meu nome é Kolder.|Serei seu motorista esta noite.
{114803}{114851}Summerfield deixou|um recado no vídeo.
{114958}{114999}Se estão assistindo isso é porque|já estou morta.
{114999}{115136}Se a Zoey estiver viva,|prometam que cuidam dela, ok?
{115136}{115201}Estou lendo o Livro de Oz toda noite.
{115201}{115338}Começamos a ler sobre o reino|de Oz. Com o Rei Gnomo.
{115421}{115493}Acho que consegui cultivar uma variante|funcional do vírus Estrela Diurna...
{115493}{115599}Como precaução, transmiti a seqüência|genética para Kolder...
{115599}{115641}Caso nosso estoque principal fosse destruído...
{115641}{115764}Para conseguir mortalidade máxima,|tem que misturá-lo com o sangue do Drake,
{115764}{115832}Bem, se funcionar...
{115832}{115920}todos os vampiros nas|proximidades devem morrer imediatamente.
{115959}{115988}Mais uma coisa...
{115988}{116035}Blade,
{116035}{116120}Precisa saber que há uma chance|do vírus destruí-lo também.
{116120}{116241}já que você é um híbrido, não sei se|seu sistema imunológico vai resistir.
{116286}{116375}Sinto muito, não tivemos tempo|suficiente para testar.
{116445}{116511}Então, vamos olhar a flecha da praga?
{116557}{116632}Só tive tempo de fabricar uma pequena|quantidade de Estrela Diurna,
{116632}{116863}No entanto, consegui equipá-lo com|um projétil de gás comprimido...
{116900}{117033}que pode ser disparado de um|dos rifles ou um arco...
{117098}{117178}De qualquer forma, tem que|fazer o disparo valer.
{117178}{117258}Não temos o suficiente para dois disparos.
{117510}{117541}Sabe quem sou?
{117541}{117584}O rei dos gnomos.
{117667}{117726}O rei dos gnomos, que doçura.
{117726}{117777}Diga-me, criança,
{117777}{117821}quer morrer?
{117821}{117898}Não tenho medo. Eu vou para o céu.
{117898}{118027}O céu não existe.|Nem Deus. Nem anjos.
{118027}{118107}A única coisa no seu futuro é o nada.
{118107}{118166}Mas e se pudesse mudar isso?
{118166}{118243}E se pudesse ser uma criança para sempre?
{118243}{118292}Não gostaria disso?
{118292}{118341}Não aceitaria esse dom?
{118391}{118439}Meus amigos estão vindo te matar.
{121674}{121709}Vai se arrepender de ter feito isso.
{121709}{121734}Por quê?
{121798}{121845}Ninguém está vindo|salvar você, Rei da Merda.
{121911}{121932}Claro que estão.
{121955}{122059}Tem uma coisa que vocês, Filhos de|uma trepada mal dada,
{122059}{122115}precisam saber sobre nós "Caçadores|Noturnos “
{122115}{122171}Quando viramos membros...
{122171}{122237}ganhamos um monte|de prêmios interessantes,
{122237}{122345}e um deles é um rastreador|implantado no corpo,
{122404}{122443}Papo furado.
{122514}{122562}Veja bem, se um de nos desaparece,
{122562}{122695}os outros ligam para um|satélite no espaço e...
{122695}{122788}Abracadabra!|Cavalaria imediata.
{122828}{122856}Gostou dessa, hein?
{122899}{122929}Vá comer sua irmã.
{122929}{123074}Ok, King, onde está este rastreador?
{123111}{123149}No lado esquerdo da minha bunda.
{123186}{123258}Ok. No lado direito da minha bunda.
{123306}{123351}Ok. Sério,
{123387}{123443}Está bem no meu rego.|Embaixo da minha tatuagem.
{123555}{123621}Abaixe minhas calças e|veja por conta própria.
{123621}{123677}Chega. Não tem mais graça.
{123677}{123734}Não é. Sua cadela vagabunda!
{123734}{123800}Mas em alguns segundos|vai ter graça.
{123800}{123907}Está vendo esta cocega no|fundo da garganta?
{123952}{123995}Minha cabeça está cheia de prata,
{123995}{124070}ela está entrando faz tempo no|sistema de ar condicionado,
{124070}{124123}Sua piranha que faz|malabarismo com caralhos.
{124357}{124520}O que significa que vocês devem estar|prontos a se foderem nesse momento.
{124717}{124748}Isso é embaraçoso.
{124798}{124836}Você tem um celular?
{125479}{125523}Uma ajuda aqui.
{126543}{126591}-Está bem?|-Sim.
{126591}{126627}-Onde está a Zoey?|-Drake está com ela.
{126763}{126789}Obrigado.
{126811}{126844}Seus brinquedos.
{126875}{126904}Vê se alcança a gente.
{129978}{130003}Abby.
{130078}{130100}Você está bem?
{130100}{130178}-Ok. Vamos tirá-la daqui.|-Cuidado!
{130695}{130731}Vá tomar no rabo!
{130807}{130867}Vou tomar no rabo de lado.
{130970}{131188}Que gracinha de carinha. Que graça de filhote.|Fique aqui. Fique.
{131188}{131234}Que sorriso lindo.
{132292}{132351}Ei, cara de pinto! Viu meu cachorro?
{132351}{132395}Já olhou no saguão?
{132472}{132493}Obrigado.
{132643}{132667}Caralho.
{132667}{132731}-Vamos, king.|-Isto-.
{133152}{133182}Blade.
{133182}{133232}Pronto para morrer?
{133323}{133367}Nasci pronto, fode-mãe.
{133439}{133505}Fode-mãe, gostei dessa.
{135852}{135891}Você quebrou meu braço.
{141244}{141304}Está pronto para morrer, fode-mãe?
{143495}{143556}Desista. Vamos.|Desista, King.
{144312}{144367}Agüenta firme, gatinha,|vou buscar ajuda.
{144630}{144669}Engraçado, não é.
{144669}{144778}Todo esse tempo meu povo tem|tentando criar um novo tipo de vampiro.
{144778}{144863}Mas um já existe.
{144863}{144946}Não preciso sobreviver.
{144946}{145031}O futuro da nossa raça cabe a você.
{145064}{145140}Você lutou com honra, eu respeito isso.
{145185}{145229}Deixe-me dar um presente de despedida,
{145229}{145388}Algo a se lembrar: mais cedo ou mais tarde,
{145388}{145485}A sede sempre vence.
{148984}{149025}E o último presente do Drake...
{149025}{149107}Digamos que o FBI conseguiu um corpo...
{149198}{149246}Só que não era o que esperavam.
{149638}{149677}Blade ainda estava por ai em algum lugar...
{149677}{149722}Fazendo aquilo que fazia melhor...
{149722}{149777}Ele era uma arma...
{149777}{149825}sua vida era uma guerra...
{149877}{149927}E todos sabem que guerra nunca acaba.
